### ISSUE TITLE
Metadata Display Issues

### ISSUE THREAD

**Issue by TkTech** [tk-technologies/ckanext-dfo#20]
- [x] Metadata description should be copied to internal `note` field to populate search descriptions.
- [x] Tables should be reworked to show long metadata fields as full-width, with the label above.
- [x] CSS is missing for compound fields, causing them to appear as one long paragraph (see contact details for example)
- [x] Composite fields ignoring field_snippet (#17)
